name: Archlinux

on:
  pull_request:
    branches:
      - master
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        kind: [static, shared]

    container: archlinux:base-devel
    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Archlinux-${{ matrix.kind }}
        cancel-in-progress: true
    steps:
      - name: Installation
        run: |
          pacman -Syu --noconfirm --needed openssl
          pacman -Sy --noconfirm --needed glibc git base-devel perl make unzip p7zip
          pacman -Sy --noconfirm --needed mesa gcc-fortran glu libc++
          git config --global --add safe.directory '*'

      - uses: actions/checkout@v1

      - name: Install XMake
        run: |
          mkdir /software && cd /software
          git clone --recursive https://github.com/TOMO-CAT/xmake.git
          cd xmake
          git checkout master
          bash scripts/install.sh
          xmake --version

      - name: Tests
        env:
          XMAKE_ROOT: y
        run: |
          xmake l ./scripts/test.lua -D -k ${{ matrix.kind }}
