name: Fedora

on:
  pull_request:
    branches:
      - master
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        kind: [static, shared]

    runs-on: ${{ matrix.os }}
    container: fedora:latest

    steps:
      - name: Installation
        run: |
          uname -a
          dnf -y install gfortran p7zip which
          dnf -y install mesa-libGL-devel mesa-libGLU-devel
          dnf -y install @development-tools @rpm-development-tools
          dnf -y install copr-cli make gcc-c++ libatomic libcxx-devel
          dnf -y upgrade git
          dnf -y install perl
          dnf -y install glibc-static libstdc++-static
          git config --global --add safe.directory /__w/xmake-repo/xmake-repo
      
      - name: Install XMake
        run: |
          mkdir /software && cd /software
          git clone --recursive https://github.com/TOMO-CAT/xmake.git
          cd xmake
          git checkout master
          bash scripts/install.sh
          xmake --version

      - uses: actions/checkout@v4
      - name: Tests
        env:
          XMAKE_ROOT: y
        run: |
          xmake l -vD ./scripts/test.lua -D -k ${{ matrix.kind }} -j4
