name: Linux

on:
  pull_request:
    branches:
      - master
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        kind: [static, shared]
        mode: [debug, release]

    runs-on: ${{ matrix.os }}
  
    steps:
      - uses: actions/checkout@v1

      - name: Install XMake
        run: |
          mkdir /software && cd /software
          git clone --recursive https://github.com/TOMO-CAT/xmake.git
          cd xmake
          git checkout master
          bash scripts/install.sh
          xmake --version

      - name: Prepare Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev p7zip gobjc gcc g++

      - name: Tests
        run: |
          xmake lua ./scripts/test.lua --diagnosis --kind=${{ matrix.kind }} --mode=${{ matrix.mode }}
