name: Linux (Clang)

on:
  pull_request:
    branches:
      - master
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        kind: [static, shared]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Install XMake
        run: |
          mkdir /software && cd /software
          git clone --recursive https://github.com/TOMO-CAT/xmake.git
          cd xmake
          git checkout master
          bash scripts/install.sh
          xmake --version

      - name: Prepare Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev p7zip

      - name: Clang Toolchain Installation
        run: |
          # https://apt.llvm.org/
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18 all

      - name: Tests
        run: |
          xmake l ./scripts/test.lua -D --toolchain=clang-18 -k ${{ matrix.kind }}
